spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/aml
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aml:
  base-url: https://allmylinks.co.uk
