spring:
  application:
    name: all-my-links
  datasource:
    url: jdbc:postgresql://localhost:5432/aml
    username: postgres
    password: postgres

aml:
  base-url: http://localhost:8080

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
