spring:
  application:
    name: all-my-links
  datasource:
    url: jdbc:mariadb://localhost:3306/aml
    username: mariadb
    password: mariadb
  mail:
    host: localhost
    port: 2525
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aml:
  base-url: http://localhost:8080
  mail-service:
    from-email: robot@allmylinks.co.uk
    from-name: AML Robot
  file-service:
    backend: DISK
    disk-storage:
      base-path: ./storage
  backoffice:
    adminEmail: robot@allmylinks.co.uk

logging:
  file:
    path: ./logs
#  level:
#    org:
#      springframework:
#        security: DEBUG
