version: '3.9'

services:
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aml
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 3000:8080

  mail:
    image: rnwood/smtp4dev
    ports:
      - 5000:80
      - 2525:25
